apiVersion: v1
kind: ConfigMap
metadata:
  name: "kube-broker-certificates"
  labels:
    {{- include "kube-broker.labels" . | nindent 4 }}
data:
  ca_cert.pem: |-
    {{ .Files.Get "files/certificates/ca_cert.pem" | nindent 4 }}
  end-entity.csr: |-
    {{ .Files.Get "files/certificates/end-entity.csr" | nindent 4 }}
  private_key.pem: |-
    {{ .Files.Get "files/certificates/private_key.pem" | nindent 4 }}
