services:
  crypto-broker-server:
    container_name: crypto-broker-server
    image: ghcr.io/open-crypto-broker/server:${TAG:-dev}
    build:
      dockerfile: docker/Dockerfile
      context: ../../../crypto-broker-server
      args:
        GOFIPS140: ${FIPS_MODE_MODULE_VERSION:-off}
    environment:
      - CRYPTO_BROKER_PROFILES_DIR=/app/profiles
      - GODEBUG=${FIPS_GODEBUG_VALUE:-fips140=off}
      - OTEL_SERVICE_NAME=test-crypto-broker-server
      - OTEL_LOGS_EXPORTER=console
      - OTEL_TRACES_EXPORTER=otlpgrpc
      - OTEL_TRACES_SAMPLER=always_on
      - OTEL_TRACES_SAMPLER_ARG=1.0
      - OTEL_METRICS_EXPORTER=console
      - OTEL_METRICS_INTERVAL=10s
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
    networks:
      - backend
    restart: always
    volumes:
      - ../../../testing/profiles:/app/profiles:ro
      - shared_data:/tmp
volumes:
  shared_data:
