name: Create-Release-Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 1.3.0)'
        required: true

permissions:
  contents: write

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Update changelog, create git tag, push to main
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          # add as GitHub actions bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # update the changelog
          git cliff --tag "$VERSION" -o CHANGELOG.md
          # remove last empty newline (no consecutive newlines, otherwise Markdown will complain)
          sed -i '${/^$/d}' CHANGELOG.md
          # create the actual commit
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG.md"
          # create a git tag
          git tag v"$VERSION"
          # push to main
          git push origin main --tags
